#General Messages Config#
Reload: '&aThe plugin &3&lGood&b&lSS&a has been reloaded'
PermissionMsg: '&cYou dont have permissions for the command'
StartSSGlobal: '&7The player &c%plss%&7 is in SS with &a%player%'
StartSS_Staff: '&7You have started the SS with &c%plss%'
LeaveSSGlobal: '&7The player &a%player%&7 has freed &a%plss%'
LeaveSS_Player: '&7The player &a%player%&7 has left you free, sorry for the inconvenience'
UnbanCorrect: '&cThis player has been unbanned correctly'
UnbanIncorrect: |-
  &cThis player is not banned
  &cOr you were wrong in name
NowInSS: '&cThis player is already in SS'
PlayerDoesNotExist: '&cThis player does not exist'
#All SS MESSAGES#
#ALERT: If the player moves a lot, he may spam messages.
SSMessageEvent: |-
  &c
  &f▇▇▇▇▇▇▇▇▇
  &f▇▇▇▇&c▇&f▇▇▇▇
  &f▇▇▇&c▇&0▇&c▇&f▇▇▇
  &f▇▇&c▇&6▇&0▇&6▇&c▇&f▇▇ &eStarted: %started%
  &f▇▇&c▇&6▇&0▇&6▇§c▇&f▇▇ &e%plss% At this moment you are in SS
  &f▇▇&c▇&6▇&0▇&6▇&c▇&f▇▇ &eIf you disconnect you will be &4&lBANNED
  &f▇&c▇&6▇▇▇▇▇&c▇&f▇ &cYou can talk in the chat or you can use /ac
  &c▇&6▇▇▇&0▇&6▇▇▇&c▇ &cWe can see your msgs and we'll answer you
  &c▇▇▇▇▇▇▇▇▇ &cYou must send your skype or add to %user%
  &f▇▇▇▇▇▇▇▇▇ &cPlayer SS: %player%
  &c
PlayerSSChatFormat: '&4&lGSS &8» &7%player% &8» &c %msg%'
#Ban messages format#
BanFormat: |-
  &d---------------------
  &d%bannedpl% banned %time%: %reason% . &5&l%player%
  &d---------------------
AutoBanReason: '(Automatic Ban)Disconnect in SS'
BanFormatDisconnect: |-
  &4You have been banned permanently(GoodSS)
  &c
  &5Banned by: &d%player%
  &5Reason: &d%reason%
  &6Date: &e%date%
  &5Time: &d%time%
  &3
  &2
  &aIf the ban was unfair
  &aWe recommend you to appeal on our page
  &2&mhttps://www.appealpage.net/
  &cIf the ban was fair
  &cWe invite you to buy your unban
  &4&mhttps://www.buypage.net/
  &c
  &3&l&k||&b&lYourServer&3&l&k||
#Inventory Format#
OpeningInventory: '&b%player% you are opening the inventory of %plss%'
#Teleport
Teleport: |-
  &cYou are teleport to:
  &4%plss%
PlayerInSS: |-
  &4%plss%&c is currently in SS
  &cPlease wait a moment
  &cDon't attack to the player please
NotBans: |-
  &cFor now, no ban has been made.
  &cThere is no one to unseat.
#List of banneds players#
BanListFormat: |-
  &c-----------------------
  &5Banned: &d%player%
  &5Reason: &d%reason%
  &5Banned by: &d%staff%
  &5Date: &d%date%
  &5Time: &d%time%
  &c-----------------------
StaffInSS: '&cYou are doing an SS!'
StaffNotInSS: '&cYou arent doing an SS!'
AdmitBan:
    int: 1
    type: minute
    reason: 'Admit the use of hacks'
    staffmsg: '&cThe player %player% has admit the use of hacks. &8Click here.'
    staffhover: '&7Ban for %int% %type%'
    # The types only can be:
    # minute
    # day
    # week
    # month
    # year
    # But cant be Seconds...
#NEW TITLES!
Titles:
    start:
        # All mesages for the title when start the SS
        ti: '&c&lYou are in SS'
        subt: '&eAnyDesk/Skype/Ts &6> &f%contact%'
        staff: '&a&lSS started'
        stsubt: '&7Wait to &8> &f%player%'
    stop:
        # All mesages for the title when stop the SS
        ti: '&a&lYou arent now in SS'
        subt: '&7Sorry for the inconvenience'
        staff: '&a&lSS stoped'
        stsubt: '&7You leave &8> &f%player%'
    admit:
        ti: '&a&lThanks for admit'
        subt: '&7You will banned for a time'
        staff: '&a&l%player% ADMIT!'
        stsubt: '&7Click on the message for tempban'
        #The ban titles only send to staff
        ban: '&c&l%player% TempBanned'
        bansubt: '&7Time: %time%'
    ban:
        #This send the title only of the staff
        ti: '&c&l%player% banned'
        subt: '&6Reason: &e%reason%'
    reload:
        # This send the message only of the executor
        ti: '&a&lPlugin reloaded!'
        subt: '&7All cache files recreateds'
