name: GoodSS
main: me.LuisArtz.SS.Main
author: LuisArtz
version: 5.0
description: The unique ScreenShare plugin of Spigot

commands:
  gss:
    description: All commands of GoodSS
  gstban:
    description: Temp ban the SS player
  admit:
    description: Admit the hacks usage
